name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: sudo docker build -t frontend .
    - name: Build the Docker remove
      run: sudo docker ps --quiet --filter="name=frontend" | xargs --no-run-if-empty sudo docker rm -f
    - name: Build the Container
      run: sudo docker run -dt -p 80:80 --restart always --name frontend frontend
